name: Build LaTeX document
on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Add files to release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: main.pdf