name: Build LaTeX document
on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
    paths:
      - '**.tex'
  pull_request:
    branches: [ main ]
    paths:
      - '**.tex'

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Commit and push PDF to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Add compiled PDF [ci skip]" || echo "No changes to commit"
          git push